# site settings
title: "Neouuid's Github Pages" 
description: "I am here to learn and share."
baseurl: ""
url: "http://git.neouuid.com"

# contact info
# email: neouuid@gmail.com
github_username: neouuid

# build settings
markdown: kramdown
theme: minima

#
page:
  list_title:"文章列表"

#exclude
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

